# Generated by Django 5.2.8 on 2025-11-30 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(verbose_name='Descripción e Historia')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='animales/')),
                ('estado', models.CharField(choices=[('ADOPCION', 'En Adopción'), ('ACOGIDA', 'Casa de Acogida'), ('ADOPTADO', 'Adoptado'), ('URGENTE', 'Urgente')], default='ADOPCION', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
